/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedMeRouteImport } from './routes/_protected/me'
import { Route as ProtectedTIndexRouteImport } from './routes/_protected/t/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTTripIdIndexRouteImport } from './routes/_protected/t/$tripId/index'
import { Route as ProtectedTTripIdChatRouteImport } from './routes/_protected/t/$tripId/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMeRoute = ProtectedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTIndexRoute = ProtectedTIndexRouteImport.update({
  id: '/t/',
  path: '/t/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTTripIdIndexRoute = ProtectedTTripIdIndexRouteImport.update({
  id: '/t/$tripId/',
  path: '/t/$tripId/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTTripIdChatRoute = ProtectedTTripIdChatRouteImport.update({
  id: '/t/$tripId/chat',
  path: '/t/$tripId/chat',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof ProtectedMeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/t/': typeof ProtectedTIndexRoute
  '/t/$tripId/chat': typeof ProtectedTTripIdChatRoute
  '/t/$tripId/': typeof ProtectedTTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof ProtectedMeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/t': typeof ProtectedTIndexRoute
  '/t/$tripId/chat': typeof ProtectedTTripIdChatRoute
  '/t/$tripId': typeof ProtectedTTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/me': typeof ProtectedMeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/t/': typeof ProtectedTIndexRoute
  '/_protected/t/$tripId/chat': typeof ProtectedTTripIdChatRoute
  '/_protected/t/$tripId/': typeof ProtectedTTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/me' | '/api/auth/$' | '/t/' | '/t/$tripId/chat' | '/t/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/me' | '/api/auth/$' | '/t' | '/t/$tripId/chat' | '/t/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/me'
    | '/api/auth/$'
    | '/_protected/t/'
    | '/_protected/t/$tripId/chat'
    | '/_protected/t/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/me': {
      id: '/_protected/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof ProtectedMeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/t/': {
      id: '/_protected/t/'
      path: '/t'
      fullPath: '/t/'
      preLoaderRoute: typeof ProtectedTIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/t/$tripId/': {
      id: '/_protected/t/$tripId/'
      path: '/t/$tripId'
      fullPath: '/t/$tripId/'
      preLoaderRoute: typeof ProtectedTTripIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/t/$tripId/chat': {
      id: '/_protected/t/$tripId/chat'
      path: '/t/$tripId/chat'
      fullPath: '/t/$tripId/chat'
      preLoaderRoute: typeof ProtectedTTripIdChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedMeRoute: typeof ProtectedMeRoute
  ProtectedTIndexRoute: typeof ProtectedTIndexRoute
  ProtectedTTripIdChatRoute: typeof ProtectedTTripIdChatRoute
  ProtectedTTripIdIndexRoute: typeof ProtectedTTripIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMeRoute: ProtectedMeRoute,
  ProtectedTIndexRoute: ProtectedTIndexRoute,
  ProtectedTTripIdChatRoute: ProtectedTTripIdChatRoute,
  ProtectedTTripIdIndexRoute: ProtectedTTripIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
