/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PRouteImport } from './routes/_p'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PMeRouteImport } from './routes/_p.me'
import { Route as PTIndexRouteImport } from './routes/_p.t.index'
import { Route as PTTripIdRouteImport } from './routes/_p.t.$tripId'
import { Route as PTTripsRouteImport } from './routes/_p.t.trips'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as PTTripIdIndexRouteImport } from './routes/_p.t.$tripId.index'
import { Route as PTTripIdChatRouteImport } from './routes/_p.t.$tripId.chat'
import { Route as ApiTripsTripIdItineraryRouteImport } from './routes/api.trips.$tripId.itinerary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PRoute = PRouteImport.update({
  id: '/_p',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PMeRoute = PMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => PRoute,
} as any)
const PTIndexRoute = PTIndexRouteImport.update({
  id: '/t/',
  path: '/t/',
  getParentRoute: () => PRoute,
} as any)
const PTTripIdRoute = PTTripIdRouteImport.update({
  id: '/t/$tripId',
  path: '/t/$tripId',
  getParentRoute: () => PRoute,
} as any)
const PTTripsRoute = PTTripsRouteImport.update({
  id: '/t/trips',
  path: '/t/trips',
  getParentRoute: () => PRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PTTripIdIndexRoute = PTTripIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PTTripIdRoute,
} as any)
const PTTripIdChatRoute = PTTripIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PTTripIdRoute,
} as any)
const ApiTripsTripIdItineraryRoute = ApiTripsTripIdItineraryRouteImport.update({
  id: '/api/trips/$tripId/itinerary',
  path: '/api/trips/$tripId/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/me': typeof PMeRoute
  '/t/$tripId': typeof PTTripIdRouteWithChildren
  '/t/trips': typeof PTTripsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/t/': typeof PTIndexRoute
  '/t/$tripId/chat': typeof PTTripIdChatRoute
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRoute
  '/t/$tripId/': typeof PTTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/me': typeof PMeRoute
  '/t/trips': typeof PTTripsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/t': typeof PTIndexRoute
  '/t/$tripId/chat': typeof PTTripIdChatRoute
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRoute
  '/t/$tripId': typeof PTTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_p': typeof PRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/_p/me': typeof PMeRoute
  '/_p/t/$tripId': typeof PTTripIdRouteWithChildren
  '/_p/t/trips': typeof PTTripsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_p/t/': typeof PTIndexRoute
  '/_p/t/$tripId/chat': typeof PTTripIdChatRoute
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRoute
  '/_p/t/$tripId/': typeof PTTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/me'
    | '/t/$tripId'
    | '/t/trips'
    | '/api/auth/$'
    | '/t/'
    | '/t/$tripId/chat'
    | '/api/trips/$tripId/itinerary'
    | '/t/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/me'
    | '/t/trips'
    | '/api/auth/$'
    | '/t'
    | '/t/$tripId/chat'
    | '/api/trips/$tripId/itinerary'
    | '/t/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_p'
    | '/about'
    | '/contact'
    | '/_p/me'
    | '/_p/t/$tripId'
    | '/_p/t/trips'
    | '/api/auth/$'
    | '/_p/t/'
    | '/_p/t/$tripId/chat'
    | '/api/trips/$tripId/itinerary'
    | '/_p/t/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PRoute: typeof PRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTripsTripIdItineraryRoute: typeof ApiTripsTripIdItineraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_p': {
      id: '/_p'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_p/me': {
      id: '/_p/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof PMeRouteImport
      parentRoute: typeof PRoute
    }
    '/_p/t/': {
      id: '/_p/t/'
      path: '/t'
      fullPath: '/t/'
      preLoaderRoute: typeof PTIndexRouteImport
      parentRoute: typeof PRoute
    }
    '/_p/t/$tripId': {
      id: '/_p/t/$tripId'
      path: '/t/$tripId'
      fullPath: '/t/$tripId'
      preLoaderRoute: typeof PTTripIdRouteImport
      parentRoute: typeof PRoute
    }
    '/_p/t/trips': {
      id: '/_p/t/trips'
      path: '/t/trips'
      fullPath: '/t/trips'
      preLoaderRoute: typeof PTTripsRouteImport
      parentRoute: typeof PRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_p/t/$tripId/': {
      id: '/_p/t/$tripId/'
      path: '/'
      fullPath: '/t/$tripId/'
      preLoaderRoute: typeof PTTripIdIndexRouteImport
      parentRoute: typeof PTTripIdRoute
    }
    '/_p/t/$tripId/chat': {
      id: '/_p/t/$tripId/chat'
      path: '/chat'
      fullPath: '/t/$tripId/chat'
      preLoaderRoute: typeof PTTripIdChatRouteImport
      parentRoute: typeof PTTripIdRoute
    }
    '/api/trips/$tripId/itinerary': {
      id: '/api/trips/$tripId/itinerary'
      path: '/api/trips/$tripId/itinerary'
      fullPath: '/api/trips/$tripId/itinerary'
      preLoaderRoute: typeof ApiTripsTripIdItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PTTripIdRouteChildren {
  PTTripIdChatRoute: typeof PTTripIdChatRoute
  PTTripIdIndexRoute: typeof PTTripIdIndexRoute
}

const PTTripIdRouteChildren: PTTripIdRouteChildren = {
  PTTripIdChatRoute: PTTripIdChatRoute,
  PTTripIdIndexRoute: PTTripIdIndexRoute,
}

const PTTripIdRouteWithChildren = PTTripIdRoute._addFileChildren(
  PTTripIdRouteChildren,
)

interface PRouteChildren {
  PMeRoute: typeof PMeRoute
  PTTripIdRoute: typeof PTTripIdRouteWithChildren
  PTTripsRoute: typeof PTTripsRoute
  PTIndexRoute: typeof PTIndexRoute
}

const PRouteChildren: PRouteChildren = {
  PMeRoute: PMeRoute,
  PTTripIdRoute: PTTripIdRouteWithChildren,
  PTTripsRoute: PTTripsRoute,
  PTIndexRoute: PTIndexRoute,
}

const PRouteWithChildren = PRoute._addFileChildren(PRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PRoute: PRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTripsTripIdItineraryRoute: ApiTripsTripIdItineraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
